title: Firefox Lockbox
author: Mozilla
email: lockbox-dev@mozilla.com
android_link: https://google.com
ios_link: https://apple.com

github_username: mozilla-lockbox

theme: minima

plugins:
  - jekyll-seo-tag

header_pages:
  - faq.md
  - privacy.md
  - process.md
  - architecture/index.md

footer_pages:
- faq.md
- privacy.md
- process.md
- architecture/index.md

include: [".well-known"]
